<a href="https://colab.research.google.com/github/dhruv-ks/MachineLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we are going to learn the basics of tensorflow.
More specifically , we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulting tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python function)
* Using GPUs with TEnsorFlow (or TPUs)

## Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7) # Creates a tensor from tensor-like object.
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check dimension of vector.
vector.ndim

1

In [6]:
# Create a matrix.
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check dimension of vector
matrix.ndim

2

In [8]:
# Create another matrix.
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) # specify the data type by dtype param
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# No. of dimensions of another_matrix.
another_matrix.ndim

2

In [10]:
# lets create a tensor.
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                      [[10,11,12],
                       [13,14,15],
                       [16,17,18]],
                      [[19,20,21],
                       [22,23,24],
                       [25,26,27]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

In [11]:
# Dimension of tensor.
tensor.ndim

3

### What we have created so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

### Creating Tensors with `tf.variable`

In [12]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Lets try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: ignored

In [15]:
# How about we try .asign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Lets try change our a=unchangeable tensor
unchangeable_tensor[0].assign(7)

AttributeError: ignored

### Creating random tensors

Random Tensors are rensors of some arbitary size which contain random numbers.

In [17]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(7) # set seed for reproduciiblity
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,2))

# Are these equal?
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a Tensor

In [18]:
# Shuffle a Tensor (Valuble for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10,7],
                            [3, 4],
                            [2, 5]])

# Shuffle the non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## HomeWork:
* Trying some random tensors
* Try to shuffle them with different methods

### Normal Distribution
Bell shaped curve, centered on mean of data and needs standard deviation(stddev).

In [20]:
tensor_normal = tf.random.Generator.from_seed(7)
tensor_normal = tensor_normal.normal((3,3), mean=4, dtype=tf.float32)
tensor_normal

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[2.6759605, 4.2878566, 3.12421  ],
       [3.91143  , 4.6921163, 4.842157 ],
       [3.936215 , 4.928008 , 3.3960211]], dtype=float32)>

### Uniform Distribution
Rectangle shaped curve, needs range of data

In [21]:
tensor_uniform = tf.random.Generator.from_seed(7)
tensor_uniform = tensor_uniform.uniform((3,3), minval=-4, maxval=4, dtype=tf.int32)
tensor_uniform

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-3, -1, -4],
       [ 2,  0,  0],
       [-2, -1,  0]], dtype=int32)>

### Shuffling stuff around
using `tf.random.shuffle` to shuffle the tensor on it's 1-Dimension

`tf.random.shuffle(value, seed=None, name=None)`

Let's see how the seed works.

In [22]:
unshuffled = tf.constant([[1,2],
                          [3,4],
                          [5,6]])
#print('not shuffled:',unshuffled)

# Shuffling things up.
tf.random.set_seed(1) # Global level random seed
tf.random.shuffle(unshuffled, seed=1) # Operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

Basically both seeds e.i. the global seed `tf.random.set_seed(n)` and operational level seed `tf.random.shuffle(unshuffled, seed=n)` is used to detrmine the randomness of a function.

Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly 
picked seed is used for this op.
2. If the graph-level seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the graph-level seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both graph-level and operation-level seeds explicitly.
3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
4.If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.


/HOMEWORK

## Other ways to create tensors.

In [23]:
tf.ones([3,3]) # Create a tensor with all ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [24]:
tf.zeros((3,3)) # Create a tensor with all zeros

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into Tensors
The main difference between NumPy arrays and TensorFlow Tensors is that tensors can be run on GPU (much faster for numerical computing)

In [25]:
# You can also turn NumPy arrays into TensorFlow tensors
import numpy as np

num_A = np.arange(1,25,dtype=np.int32) # Create a numpy array between 1 and 25
num_A

#X = tf.constant(matrix) # Capital for matrix or tensor
#y = tf.constant(vector) # Smaller for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A = tf.constant(num_A, shape = (2,3,4))
B = tf.constant(num_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting information from tensors
* Shape
* Size
* Rank
* Axis

In [27]:
# Create a rank 4 tensor (4 Dimension)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# Get varios attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimension(rank)", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total no. of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimension(rank) 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along last axis: 5
Total no. of elements in tensor: 120


## Indexing tensors
Tensors can be indexed just like Python list.

In [30]:
# Get first 2 element of each dimension.
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# Get the element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:].numpy()

array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)

In [32]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [33]:
# Get the last item of each row of rank_2_tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [34]:
# Adding extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... means after all axises
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [35]:
# Alternative to tf.newaxis
print(rank_2_tensor)

tf.expand_dims(rank_2_tensor, axis=-1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating tensors (tensor operation)


#### Basic operations

`+, -, *, /`

In [36]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [37]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [38]:
# Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [39]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [40]:
# We can use the TensorFlow too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**TensorFlow operators are fast**

In [41]:
tf.add(tensor,12)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 19],
       [15, 16]], dtype=int32)>

#### Matrix Multplication

In machine learning, matrix multiplication is one of the most common operation

```python
tf.linalg.matmul(
    a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False,
    a_is_sparse=False, b_is_sparse=False, name=None
)
```

In [42]:
# Matrix multiplication in TensorFlow.
print(tensor)
tf.matmul(tensor, tensor)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [43]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
# Create a tensor (3,2)
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
# Create another (3,2)
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [45]:
X @ Y

InvalidArgumentError: ignored

In [48]:
# Let's reshape the Y
Y
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [49]:
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
# Can do the same with transpose
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

**The Dot Produt**
Matrix multiplication is also reffered to as dot product.

we can perform matrix multiplication using:
- `tf.matmul()`
- `tf.tensordot()`
- `@`

In [59]:
print(tf.tensordot(X, Y, 0))
X,Y

tf.Tensor(
[[[[ 7  8]
   [ 9 10]
   [11 12]]

  [[14 16]
   [18 20]
   [22 24]]]


 [[[21 24]
   [27 30]
   [33 36]]

  [[28 32]
   [36 40]
   [44 48]]]


 [[[35 40]
   [45 50]
   [55 60]]

  [[42 48]
   [54 60]
   [66 72]]]], shape=(3, 2, 3, 2), dtype=int32)


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

**Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy multiplication rules.**

#### Changing the datatype of a tensor

`tf.cast(tensor, dtype)`

In [51]:
# Create a new tensor with default datatype(float32)
B = tf.constant([1.7,2.8])
B.dtype

tf.float32

In [52]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [53]:
# Change from float32 to float16

D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 2.8], dtype=float16)>

In [54]:
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

#### Aggregating tensors

Aggregating tensor is condensing them from moltiple values down to smaller amount of values

In [60]:
# Get the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [62]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [70]:
# Creating a random tensor with value between 0 and 100 of size 50
E = tf.constant(np.random.randint(1,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([17, 60, 10, 59, 99, 98, 93, 30, 13, 79, 24, 56, 60, 25, 56, 75, 23,
       83, 82, 60, 31, 13, 28, 53, 86, 38, 57,  2, 62, 71, 65, 47, 29, 63,
       61, 74, 67, 51, 90, 12, 44, 62, 57, 36, 96, 94, 71, 30, 28, 28])>

In [71]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [72]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [73]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [74]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [75]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2648>

In [76]:
tf.reduce_prod(E)

<tf.Tensor: shape=(), dtype=int64, numpy=8305095109708349440>

In [81]:
mean_E = tf.reduce_sum(E)/tf.size(E).numpy()
mean_E

<tf.Tensor: shape=(), dtype=float64, numpy=52.96>

In [82]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [91]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=687.9584>

In [92]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32)).numpy()

26.22896

#### Find the positional maximum and minimum

In [108]:
# Create a new Tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [109]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [110]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [111]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [113]:
#### Squeezing a tensor (removing all single dimensions)
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [114]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [115]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

#### One hot encoding


In [117]:
# Create a list of indices
some_list = [0,1,2,3] # Could be red, green, blue, purple

# One-Hot encode our some_list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [118]:
# Specify Custom value for one-hot encoding
tf.one_hot(some_list, depth=4, on_value=True, off_value=False)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

In [126]:
test_list = [1,4,5,2,7]
tf.one_hot(test_list, depth=8)

<tf.Tensor: shape=(5, 8), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

#### Squaring, Log, Square root

In [127]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [128]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [133]:
# Square root
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [136]:
# Find the log
tf.math.log(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy
TensorFlow interacts beutifully with numpy array.

In [137]:
 # Create a tensor directly from a NumPy array
 J = tf.constant(np.array([3.,7.,10]))
 J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [138]:
# Convert tensor back to NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [139]:
J.numpy()

array([ 3.,  7., 10.])

In [142]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Extras and Co-curriculum

## Exercise

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [145]:
scalar_E = tf.constant(1)
scalar_E, scalar_E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, 0)

In [146]:
vector_E = tf.constant([3,7,10])
vector_E, vector_E.ndim

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 10], dtype=int32)>,
 1)

In [147]:
matrix_E = tf.constant([[1,2,3],
                        [4,5,6]])
matrix_E, matrix_E.ndim

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, 2)

In [148]:
tensor_E = tf.constant([[[1,2,3],
                        [4,5,6]],
                        
                        [[1,2,3],
                         [4,5,6]]])
tensor_E, tensor_E.ndim

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]], dtype=int32)>, 3)

2. Find the shape, rank and size of the tensors you created in 1

In [150]:
print(scalar_E.shape, scalar_E.ndim, tf.size(scalar_E),'\n')
print(vector_E.shape, vector_E.ndim, tf.size(vector_E),'\n')
print(matrix_E.shape, matrix_E.ndim, tf.size(matrix_E),'\n')
print(tensor_E.shape, tensor_E.ndim, tf.size(tensor_E),'\n')

() 0 tf.Tensor(1, shape=(), dtype=int32) 

(3,) 1 tf.Tensor(3, shape=(), dtype=int32) 

(2, 3) 2 tf.Tensor(6, shape=(), dtype=int32) 

(2, 2, 3) 3 tf.Tensor(12, shape=(), dtype=int32) 



3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`

In [151]:
#tf.random.set_seed(7)
random_1_E = tf.random.uniform([5,300])
random_2_E = tf.random.uniform([5,300])
random_1_E, random_2_E

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

4. Multiply the two tensors you created in 3 using matrix multiplication

In [154]:
tf.matmul(random_1_E,random_2_E, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71401 , 80.87824 , 78.32848 , 78.2597  , 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.2774  ],
       [75.16001 , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.11356 , 75.401215, 72.79378 , 75.066376, 75.20653 ],
       [79.87285 , 83.40139 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product

In [161]:
tf.tensordot(random_1_E,tf.transpose(random_2_E), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71401 , 80.87824 , 78.32848 , 78.2597  , 79.130585],
       [70.12708 , 72.09945 , 70.1678  , 73.24609 , 74.2774  ],
       [75.16001 , 79.52858 , 76.74644 , 78.14265 , 77.28679 ],
       [77.11356 , 75.401215, 72.79378 , 75.066376, 75.20653 ],
       [79.87285 , 83.40139 , 78.57373 , 79.025894, 81.82093 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`

In [163]:
tf.random.set_seed(7)
random_3_E = tf.random.uniform([224,224,3])
random_3_E

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8344538 , 0.23336661, 0.8796519 ],
        [0.04664922, 0.80349684, 0.9420098 ],
        [0.48560476, 0.9596517 , 0.65881574],
        ...,
        [0.5860318 , 0.48737013, 0.7365041 ],
        [0.4669237 , 0.32675016, 0.7892678 ],
        [0.06122839, 0.81435096, 0.7064053 ]],

       [[0.43275082, 0.26824856, 0.69550574],
        [0.8685899 , 0.28069723, 0.39523184],
        [0.19567001, 0.40724087, 0.04454517],
        ...,
        [0.43178904, 0.69221234, 0.2229476 ],
        [0.7250947 , 0.3481722 , 0.04613721],
        [0.99625635, 0.56748664, 0.5955579 ]],

       [[0.56123173, 0.12232518, 0.8995544 ],
        [0.33412373, 0.5526645 , 0.19505835],
        [0.29208362, 0.15077579, 0.75069475],
        ...,
        [0.46821463, 0.80908   , 0.17361856],
        [0.12702239, 0.2896787 , 0.9261279 ],
        [0.40931833, 0.1861794 , 0.4138496 ]],

       ...,

       [[0.84302187, 0.6846659 , 0.5883076 ],
        [0.95

7. Find the min and max values of the tensor you created in 6

In [164]:
tf.reduce_min(random_3_E),tf.reduce_max(random_3_E)

(<tf.Tensor: shape=(), dtype=float32, numpy=5.2452087e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999931>)

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`

In [166]:
random_4_E = tf.random.uniform([1,224,224,3])
random_4_E

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[1.90534592e-02, 6.49655104e-01, 6.96206927e-01],
         [5.50074816e-01, 5.88577747e-01, 2.47053385e-01],
         [3.29534411e-01, 1.12019897e-01, 6.46760821e-01],
         ...,
         [6.05453014e-01, 2.26416945e-01, 1.02378845e-01],
         [3.78343225e-01, 5.46195269e-01, 3.60101581e-01],
         [2.96108603e-01, 1.42966509e-02, 3.71624827e-01]],

        [[3.70490432e-01, 9.95367646e-01, 3.14680219e-01],
         [9.76846576e-01, 1.33267164e-01, 9.98384356e-01],
         [7.33183861e-01, 5.36768556e-01, 4.62296009e-02],
         ...,
         [1.98324561e-01, 6.40800714e-01, 5.96124768e-01],
         [1.88073635e-01, 9.70675111e-01, 5.17419577e-01],
         [9.79518294e-01, 5.51191568e-02, 9.73463058e-04]],

        [[6.49672747e-02, 4.38274741e-01, 5.81417084e-02],
         [3.69277596e-01, 9.35164690e-01, 4.71378088e-01],
         [2.00963020e-01, 7.59706616e-01, 2.72475958e-01],
         ...,
         [3

In [167]:
tf.squeeze(random_4_E)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[1.90534592e-02, 6.49655104e-01, 6.96206927e-01],
        [5.50074816e-01, 5.88577747e-01, 2.47053385e-01],
        [3.29534411e-01, 1.12019897e-01, 6.46760821e-01],
        ...,
        [6.05453014e-01, 2.26416945e-01, 1.02378845e-01],
        [3.78343225e-01, 5.46195269e-01, 3.60101581e-01],
        [2.96108603e-01, 1.42966509e-02, 3.71624827e-01]],

       [[3.70490432e-01, 9.95367646e-01, 3.14680219e-01],
        [9.76846576e-01, 1.33267164e-01, 9.98384356e-01],
        [7.33183861e-01, 5.36768556e-01, 4.62296009e-02],
        ...,
        [1.98324561e-01, 6.40800714e-01, 5.96124768e-01],
        [1.88073635e-01, 9.70675111e-01, 5.17419577e-01],
        [9.79518294e-01, 5.51191568e-02, 9.73463058e-04]],

       [[6.49672747e-02, 4.38274741e-01, 5.81417084e-02],
        [3.69277596e-01, 9.35164690e-01, 4.71378088e-01],
        [2.00963020e-01, 7.59706616e-01, 2.72475958e-01],
        ...,
        [3.64496350e-01, 8.07347

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value

In [169]:
tensor_E_1 = tf.constant([1,2,3,4,5,6,7,8,9,10])
tensor_E_1.shape

TensorShape([10])

10. One-hot encode the tensor you created in 9

In [172]:
tf.one_hot(tensor_E_1,11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>